/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */

import javax.swing.table.DefaultTableModel;


public class Date extends javax.swing.JFrame {  
    String [] agenda = new String[7];
    
    /**
     * Creates new form Date
     */
    public Date() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        Hari = new javax.swing.JLabel();
        Agenda = new javax.swing.JLabel();
        Selesai = new javax.swing.JLabel();
        Mulai = new javax.swing.JLabel();
        tMulai = new javax.swing.JTextField();
        tAgenda = new javax.swing.JTextField();
        waktu = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        SO = new javax.swing.JTextField();
        DSK = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        MATEK = new javax.swing.JTextField();
        Et = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        Fis = new javax.swing.JTextField();
        TMIKRO = new javax.swing.JTextField();
        KWU = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        PROSTAT = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        ORKOM = new javax.swing.JTextField();
        PPB = new javax.swing.JTextField();
        el = new javax.swing.JTextField();
        TAP = new javax.swing.JTextField();
        PBO = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        ADD = new javax.swing.JLabel();
        tMulai1 = new javax.swing.JTextField();
        tHari = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        sen = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        sel = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        rab = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        kam = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        jum = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        sab = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        ming = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date ");

        jPanel15.setBackground(new java.awt.Color(248, 248, 248));

        Hari.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Hari.setText("Hari");

        Agenda.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Agenda.setText("Agenda");

        Selesai.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Selesai.setText("Selesai");

        Mulai.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Mulai.setText("Mulai");

        tMulai.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        tAgenda.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        waktu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setText(" Mulai-selesai");

        jTextField33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText("-");

        SO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SO.setText("SO");
        SO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOActionPerformed(evt);
            }
        });

        DSK.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DSK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DSK.setText("DSK");
        DSK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DSKMouseEntered(evt);
            }
        });
        DSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSKActionPerformed(evt);
            }
        });

        jTextField38.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("-");

        MATEK.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        MATEK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MATEK.setText("MATEK");
        MATEK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MATEKMouseEntered(evt);
            }
        });

        Et.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Et.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Et.setText("-");
        Et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EtMouseEntered(evt);
            }
        });

        jTextField41.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField41.setText("-");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setText("SENIN");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel41.setText("SELASA");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel42.setText("MINGGU");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel43.setText("KAMIS");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel44.setText("RABU");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel45.setText("SABTU");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel46.setText("JUMAT");

        jTextField34.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setText("-");

        jTextField35.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setText("-");

        Fis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Fis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fis.setText("-");
        Fis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FisMouseEntered(evt);
            }
        });
        Fis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FisActionPerformed(evt);
            }
        });

        TMIKRO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TMIKRO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TMIKRO.setText("T.MIKRO");
        TMIKRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TMIKROMouseEntered(evt);
            }
        });
        TMIKRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMIKROActionPerformed(evt);
            }
        });

        KWU.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        KWU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        KWU.setText("KWU");
        KWU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KWUMouseEntered(evt);
            }
        });
        KWU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KWUActionPerformed(evt);
            }
        });

        jTextField46.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField46.setText("-");

        jTextField47.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField47.setText("-");

        PROSTAT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PROSTAT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PROSTAT.setText("PROSTAT");
        PROSTAT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PROSTATMouseEntered(evt);
            }
        });

        jTextField49.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField49.setText("-");

        ORKOM.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ORKOM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ORKOM.setText("ORKOM");

        PPB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PPB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PPB.setText("PPB");
        PPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PPBMouseEntered(evt);
            }
        });

        el.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        el.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        el.setText("RPL");
        el.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elMouseEntered(evt);
            }
        });
        el.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elActionPerformed(evt);
            }
        });

        TAP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TAP.setText("TAP");
        TAP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TAPMouseEntered(evt);
            }
        });
        TAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAPActionPerformed(evt);
            }
        });

        PBO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        PBO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PBO.setText("PBO");
        PBO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PBOMouseEntered(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("TIME");

        ADD.setBackground(new java.awt.Color(0, 0, 153));
        ADD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ADD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADD.setText("Add");
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
        });

        tMulai1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        tHari.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        sen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SENIN"
            }
        ));
        jScrollPane12.setViewportView(sen);

        sel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELASA"
            }
        ));
        jScrollPane13.setViewportView(sel);

        rab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RABU"
            }
        ));
        jScrollPane14.setViewportView(rab);

        kam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KAMIS"
            }
        ));
        jScrollPane15.setViewportView(kam);

        jum.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JUMAT"
            }
        ));
        jScrollPane16.setViewportView(jum);

        sab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SABTU"
            }
        ));
        jScrollPane17.setViewportView(sab);

        ming.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ming.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MINGGU"
            }
        ));
        jScrollPane18.setViewportView(ming);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(Selesai)
                                .addGap(18, 18, 18)
                                .addComponent(tMulai1))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Agenda)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                            .addComponent(Hari)
                                            .addGap(29, 29, 29)))
                                    .addComponent(Mulai))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(tAgenda)
                                    .addComponent(tHari))))
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(waktu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(KWU, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PBO, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TAP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addComponent(ORKOM, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(PROSTAT, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TMIKRO, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addComponent(jTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(PPB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(el, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel15Layout.createSequentialGroup()
                                                .addComponent(Fis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel15Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(SO, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(DSK, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MATEK, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(Et, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(229, 229, 229))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel40)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel41)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel44)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel43)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel46)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel45)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel42)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(jLabel42)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MATEK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Et, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KWU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waktu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TMIKRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PROSTAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ORKOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(el, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Hari)
                                    .addComponent(tHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Agenda)
                                    .addComponent(tAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Mulai)
                                    .addComponent(tMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Selesai)
                            .addComponent(tMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void KWUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KWUMouseEntered
        // TODO add your handling code here:
        waktu.setText("07.00-08.40");

    }//GEN-LAST:event_KWUMouseEntered

    private void TAPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TAPMouseEntered
        waktu.setText("08.50-10.30");
    }//GEN-LAST:event_TAPMouseEntered

    private void DSKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSKMouseEntered
        waktu.setText("09.40-11.20");
    }//GEN-LAST:event_DSKMouseEntered

    private void PROSTATMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROSTATMouseEntered
        waktu.setText("12.40-15.10");
    }//GEN-LAST:event_PROSTATMouseEntered

    private void PPBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPBMouseEntered
        waktu.setText("15.10-16.50");
    }//GEN-LAST:event_PPBMouseEntered

    private void MATEKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MATEKMouseEntered
        waktu.setText("06.30-08.10");
    }//GEN-LAST:event_MATEKMouseEntered

    private void TMIKROMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMIKROMouseEntered
        waktu.setText("08.50-10.30");
    }//GEN-LAST:event_TMIKROMouseEntered

    private void elMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elMouseEntered
        waktu.setText("14.20-16.50");
    }//GEN-LAST:event_elMouseEntered

    private void EtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtMouseEntered
        waktu.setText("07.00-08.40");
    }//GEN-LAST:event_EtMouseEntered

    private void FisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FisMouseEntered
        waktu.setText("09.30-11.10");
    }//GEN-LAST:event_FisMouseEntered

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
        DefaultTableModel model1 = (DefaultTableModel)sen.getModel();
        DefaultTableModel model2 = (DefaultTableModel)sel.getModel();
        DefaultTableModel model3 = (DefaultTableModel)rab.getModel();
        DefaultTableModel model4 = (DefaultTableModel)kam.getModel();
        DefaultTableModel model5 = (DefaultTableModel)jum.getModel();
        DefaultTableModel model6 = (DefaultTableModel)sab.getModel();
        DefaultTableModel model7 = (DefaultTableModel)ming.getModel();

        if (null != tHari.getText())switch (tHari.getText()) {
            case "Senin":
            model1.addRow(new Object[]{tAgenda.getText()});
            break;
            case "Selasa":
            model2.addRow(new Object[]{tAgenda.getText()});
            break;
            case "Rabu":
            model3.addRow(new Object[]{tAgenda.getText()});
            break;
            case "Kamis":
            model4.addRow(new Object[]{tAgenda.getText()});
            break;
            case "Jumat":
            model5.addRow(new Object[]{tAgenda.getText()});
            break;
            case "Sabtu":
            model6.addRow(new Object[]{tAgenda.getText()});
            break;
            case "Minggu":
            model7.addRow(new Object[]{tAgenda.getText()});
            break;
            default:
            break;
        }
    }//GEN-LAST:event_ADDMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Home i = new Home();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void KWUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KWUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KWUActionPerformed

    private void TAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAPActionPerformed

    private void SOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SOActionPerformed

    private void DSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DSKActionPerformed

    private void TMIKROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMIKROActionPerformed
        // TODO add your handling code here:
        waktu.setText("10.40-13.10");
    }//GEN-LAST:event_TMIKROActionPerformed

    private void PBOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PBOMouseEntered
        waktu.setText("10.40-13.10");
    }//GEN-LAST:event_PBOMouseEntered

    private void FisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FisActionPerformed

    private void elActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ADD;
    private javax.swing.JLabel Agenda;
    private javax.swing.JTextField DSK;
    private javax.swing.JTextField Et;
    private javax.swing.JTextField Fis;
    private javax.swing.JLabel Hari;
    private javax.swing.JTextField KWU;
    private javax.swing.JTextField MATEK;
    private javax.swing.JLabel Mulai;
    private javax.swing.JTextField ORKOM;
    private javax.swing.JTextField PBO;
    private javax.swing.JTextField PPB;
    private javax.swing.JTextField PROSTAT;
    private javax.swing.JTextField SO;
    private javax.swing.JLabel Selesai;
    private javax.swing.JTextField TAP;
    private javax.swing.JTextField TMIKRO;
    private javax.swing.JTextField el;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTable jum;
    private javax.swing.JTable kam;
    private javax.swing.JTable ming;
    private javax.swing.JTable rab;
    private javax.swing.JTable sab;
    private javax.swing.JTable sel;
    private javax.swing.JTable sen;
    private javax.swing.JTextField tAgenda;
    private javax.swing.JTextField tHari;
    private javax.swing.JTextField tMulai;
    private javax.swing.JTextField tMulai1;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
